###
POST http://127.0.0.1:5000/rest/text-analytics
Content-Type: application/json

{
    "question": "Ich habe im letzen Jahr geheiratet, was muss ich beachten?"
}

###
POST http://127.0.0.1:5000/rest/text-analytics
Content-Type: application/json

{
"question": "Ich habe Eigenleistungen an meinem Grundstück erbracht, was muss ich beachten?"
}

###
POST http://127.0.0.1:5000/rest/text-analytics
Content-Type: application/json

{
  "question": "Muss ich als Hausbesitzer den Eigenmietwert zusätzlich zum Einkommen versteuern? Falls ja, wie wird er ermittelt? Und gibt es Regeln für Ausnahmen?"
}

###
POST http://127.0.0.1:5000/rest/text-analytics
Content-Type: application/json

{
  "question": "Spannend, erkläre mir bitte alle Details zu der Härtefallregelung bei der Eigenmietwertbesteuerung."
}

###
POST http://127.0.0.1:5000/rest/text-analytics
Content-Type: application/json

{
  "question": "Zeige mir alle relevanten Punkte auf, die es im Zusammenhang mit Kindern und Steuern zu beachten gibt."
}

###
POST http://127.0.0.1:5000/rest/text-analytics
Content-Type: application/json

{
  "question": "Können Kosten, die im Zusammenhang mit der Ausübung meines Berufs entstehen, von den Steuern abgezogen werden? Falls ja, was muss ich beachten?"
}

###
POST http://127.0.0.1:5000/rest/text-analytics
Content-Type: application/json

{
  "question": "Sind Einkünfte aus Liegenschaften relevant für die Steuern? Falls ja, was muss ich beachten?"
}

###
POST http://127.0.0.1:5000/rest/text-analytics
Content-Type: application/json

{
"question": "Gib mir eine Übersicht über alle Kosten, die ich bei unselbständiger Erwerbstätigkeit von den Steuern abziehen kann."
}